public class apexclass {

    public static void demo(){
   demo2(5, 'king');
        demo3('patel');
        
    }
    public static void demo2(integer k, string s){
     //   system.debug('demo value :' +k);
     //   integer a =2;
     //   system.debug('a value : '+ a);
            system.debug('demo k value :' +k );
        system.debug('demo  s value :' +s );
    }
    
    
    public static void demo3( string c){
        system.debug('demo3 value :'+c );
        string b ='dhruvil';
        system.debug('string value :' +b);
    }
}