public class arrayp1 {
    
    
    public static void maain1(){
        
        Integer  [] Account  = new list<Integer>{13,56,78,34,67,88};
            
            for(integer i=0; i<Account.size();  i++){
                system.debug('enter');
                if(i >=57){
                    system.debug('value is below 57 :' + i);
                }else if (i <=78 ){
                    system.debug('value is below 78 :'+i);
                    
                }else{
                    system.debug('print is else');
                }
                system.debug('this is array'+ account); 
            }
        
        
        
        
    }
}