public class arrayname {

    
    public static void d1(){

    //Defining array
/* String [] arrayOfProducts = new List<String>();

//Adding elements in Array
arrayOfProducts.add('HCL');
arrayOfProducts.add('H2SO4');
arrayOfProducts.add('NACL');
arrayOfProducts.add('H2O');
arrayOfProducts.add('N2');
arrayOfProducts.add('U296');

for (Integer i = 0; i<arrayOfProducts.size(); i++) {
   //This loop will print all the elements in array
   system.debug('Values In Array: '+arrayOfProducts[i]);
} */
        
       integer [] array1 = new list<integer>();
        
        array1.add(78);
        array1.add(781);
        array1.add(718);
        array1.add(178);
        array1.add(784);
        array1.add(738);
        for(integer i =0; i<array1.size(); i++){
            system.debug('integer array :'+ array1[i]);
        }
    }
}