public  virtual class car {
    
    
    private integer Maruti = 60;
    private integer Alto = 70;
    private integer  Brezza =80;
    
    public virtual void speed(){
        system.debug('Speed is :');
    }
    
    public virtual integer getMaruti(){
        return Maruti;
    }
      public virtual integer getAlto(){
        return Alto;
    }
    
      public virtual integer getBrezza(){
        return Brezza;
    }
    
    

}