public class classmethod {
 
  /*  public static void num(){
        list<integer> dhruvil = new list<integer>();
       integer  maxnum = 6;
        
        for(integer i = 0; i <= maxnum; i++){
            dhruvil.add(i);
        }
        system.debug(dhruvil);
    }  */
    
   /* public static void mapmeth(){
        map<integer,string> dh = new map <integer, string>();
       dh.put(1, 'one');
        dh.put(2, 'two');
        dh.put(3,'three');
        
        system.debug(dh.get(3));  
    } */
    
    /*public static void collection(){
        list<integer> name = new list<integer>();
        	
 
        name.add(78);
        name.add(91);  
          name.add(9431); 
          name.add(9341);   
        name.add(931); 
        
        
       name.set(0,123);
       name.set(1,21);
        name.set(1,05);
        name.set(4,78);
            system.debug(name);
        
    }*/
    
   /* public static void method(){
          list<string> name = new list<string>();
        
     name.add('hello');
          name.add('how');
          name.add('are');
          name.add('you'); 
        
        name.set(1,'where');
        system.debug(name);
        
    }
    
     public static void mapsort(){
        list<integer> s1 = new list<integer>(); 
        s1.add(78);
        s1.add(91);  
          s1.add(9431); 
          s1.add(9341);   
        s1.add(931); 
         s1.sort();
         system.debug(s1);
     }
       public static void clr(){
        list<integer> s1 = new list<integer>(); 
        s1.add(78);
        s1.add(91);  
          s1.add(9431); 
          s1.add(9341);   
        s1.add(931); 
         s1.clear();
         system.debug(s1);
     } */
     /*    public static void eamptee(){
        list<integer> s1 = new list<integer>(); 
        s1.add(78);
        s1.add(91);  
          s1.add(9431); 
          s1.add(9341);   
        s1.add(931); 
         s1.isEmpty();
         system.debug(s1);
             s1.isEmpty();
             system.debug(s1);
     }*/
    
   /* public static void setobj(){
        set<Account> s1 = new set <Account>();
        
        Account a1 = new Account (Name = 'amazon', NumberOfEmployees = 20000 );
        Account a2 = new Account (Name = 'flipcart', NumberOfEmployees = 15000);
        Account a3 = new Account (Name = 'google', NumberOfEmployees = 19000);
        Account a4 = new Account (Name = 'tata', NumberOfEmployees = 16000);
        
        s1.add(a1);
        s1.add(a2);
        system.debug(s1.size());
        
    }*/
    
   /* public static void setmeth(){
     list <integer> aa1 = new list <integer>{3,4,5,6,7};
          list <integer> s2 = new list <integer>{2,8,9,12}; 
       
        s2.addAll(aa1);
        system.debug(s2);
         system.debug(s2.contains(4));
         system.debug(s2.contains(15));
          // system.debug(s2.containsAll(aa1));
           system.debug(s2.size());
       // system.debug(s2.retainAll(s2));
       
     
       
    }*/
    
    
        
    
}