public class myfirstlist{

  /*  public static void firstlistex(){
        List<integer> myfirstinteger = new List<integer>();
        
        myfirstinteger.add(12);
        myfirstinteger.add(15);
       system.debug(myfirstinteger);
    } */
   

   /* public static void listmethod(){
        List<string> firststring = new List<string>();
        firststring[0] = 'dhruvil';
        firststring[1] = 'smit';
        firststring[2] = 'dhrunal';
        
       string name = firststring.remove(1);
       
        System.debug(name);
        
    }*/
    
    
   /* public static void seclist(){ 
    List<Integer> myList = new List<Integer>();
	myList.add(47);
	Integer myNumber = myList.get(0);
 system.debug(myNumber);
    } */
    
   /* public static void method1(){
        List<string> dhruv = new List<string>();
        dhruv[0] = 'smit';
        dhruv[1] = 'dhrunal';
        dhruv.sort();
        system.debug(dhruv);
        
    }*/
    
  /*  public static void object1(){
        Set <string> first = new Set <string> {'dhruv','smit','dhrunal'};
            first.add('vaibhav');
        first.size();
        //first.clear();
         //first.remove('smit');
 
         
        first.contains('vaibhav');
       
    system.debug(first);
        
    }
    */
   /* public static void mapcollact(){
        
    /*    Map <string,string> mynum = new Map <string,string>();
        mynum.put('34', '67');
        mynum.put('38', '68');
        system.debug(mynum);*/
        
            /*  Map <integer,integer> mynum = new Map <integer,integer>();
        mynum.put(34, 67);
        mynum.put(38, 69);
        system.debug(mynum);*/
        
       /* map<integer,string> name = new map <integer, string> ();
        name.put(34,'dhruvil');
        name.put(65, 'vegad');
       // name.remove(34);
      // name.size();
      name.get(34);
       system.debug(name);
        
            }*/
        
      /* public  static void myname(){
           list<Account> Accts = new list<Account>();
           Accts.add(new Account(Name='Account1'));
           Accts.add(new Account(Name='Account2'));
               insert Accts;
           Map<Id, Account> m = new Map<Id, Account>();
			m.putAll(Accts);
             system.debug(m);
        }*/
    
    


      integer  x; 
     
    public myfirstlist(){
     x =90;        
    }
    public void show(){
        system.debug(x);
    	}
	 
}