public class mylist {
  /*  public static void myMethod(){
        String msg = 'Original value';
        
        newaddString(msg);
        system.assertEquals(msg, 'Original value');
       
        
    }*/
    
    public static void firstlist(){
        List<string> firstlist = new List<string>();
        firstlist[0] ='dhruvil';
        firstlist[1] = 'smit';
        firstlist[2] = 'dhrunal';
        
      string s1 =  firstlist.remove(1);
        system.debug(s1);
        
    }
    
   /* public static void newaddString(String s){
        s ='Modified value';
    }*/
}