public class stringmethod {
    
    
    /* public static void stingmeth(){
set<integer> strset = new set<integer>{56,78,34,89};
set<integer> strset1 = new set<integer>();
strset1=strset.clone();
system.debug(strset1);
system.debug(strset.contains(56));
} */
    
    public static void stimeth(){
        
        string str = 'dhruvil';
        string str2 = 'Dhruvil';
        system.debug(str.capitalize());
        system.debug(str.trim());
        system.debug(str.substringafterlast('.')); 
        
        system.debug(str.equals(str2));
        
        system.debug(str.contains('ring'));
        
        system.debug(str.toLowerCase(str2));
        
        system.debug(str.toUpperCase(str));
        
        system.debug(str.split(''));
        
        system.debug(str.replace('dhruvil','smit'));
        
     /*   integer myinteger = 345;
       string sinteger = string.valueOf(myinteger);
        system.debug(sinteger);
        
        Date myDate = Date.today();
        string sDate = String.valueOf(myDate);
        system.debug(sDate);
        
        string s = 'hello';
        string s2 = s.center(90);
        system.debug(s2);
        
        string s1 = 'hello dhruvil';
        string s3 = s1.abbreviate(4);
        system.debug(s3);
*/
         }
}